package model

type AutoGenerated struct {
	VersionInfo    string `json:"VersionInfo"`
	SocketError    string `json:"SocketError"`
	Time           string `json:"Time"`
	UserID         string `json:"UserID"`
	DeviceID       string `json:"DeviceID"`
	CurrentLine    string `json:"CurrentLine"`
	ApiSpeed       string `json:"ApiSpeed"`
	ContractSpeed  string `json:"ContractSpeed"`
	LaunchTime     string `json:"LaunchTime"`
	NetError       string `json:"NetError"`
	URL            string `json:"URL"`
	AppStatus      string `json:"AppStatus"`
	Name           string `json:"name"`
	OnClick        string `json:"onClick"`
	EventID        string `json:"eventID"`
	ApiCallTime    string `json:"ApiCallTime"`
	ResponseTime   string `json:"responseTime"`
	Error300Report string `json:"error300Report"`
}

//ApiCallTime
// ApiResponseTime
// error300Report

type DeviceIdentifiers struct {
	Idfv string `json:"idfv"`
}
