package main

import (
	"encoding/csv"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"demo/model"
)

var (
	filePaths       string = ""
	uuid            string = ""
	name            string
	count           int    = 0
	Filecount       int    = 0
	fileName        string = "/AllData.csv"
	fileName2       string = "/AllData.csv"
	VersionInfo            = ""
	SocketError            = ""
	Time                   = ""
	UserID                 = ""
	DeviceID               = ""
	CurrentLine            = ""
	ApiSpeed               = ""
	ContractSpeed          = ""
	LaunchTime             = ""
	NetError               = ""
	URL                    = ""
	AppStatus              = ""
	Name                   = ""
	OnClick                = ""
	EventID                = ""
	ApiCallTime            = ""
	ApiResponseTime        = ""
	error300Report         = ""
)

func main() {
	filePaths = getAbsPath() //檔案路徑
	checkNumber()
	checkFileName()

	csvFile, err := os.Create(filePaths + fileName)   //產生新的檔名
	csvFile2, err := os.Create(filePaths + fileName2) //產生新的檔名
	if err != nil {
		panic(err)
	}
	defer csvFile.Close()
	file, err := os.Open(filePaths + "/weex.csv") //讀取原始檔案

	if err != nil {
		log.Fatalf("Error when opening file: %s", err)
	}
	//weexraw

	readFile := csv.NewReader(file)
	readFile.Comma = ','          // 以何種字元作分隔，預設為`,`
	readFile.FieldsPerRecord = -1 //防止錯誤
	csvFile.Seek(0, io.SeekEnd)
	csvFile.WriteString("\xEF\xBB\xBF") // 寫入UTF-8 防止中文亂碼
	writer := csv.NewWriter(csvFile)
	writer.Comma = ','
	writer.UseCRLF = true

	csvFile2.Seek(0, io.SeekEnd)
	csvFile2.WriteString("\xEF\xBB\xBF") // 寫入UTF-8 防止中文亂碼
	writer2 := csv.NewWriter(csvFile2)
	writer2.Comma = ','
	writer2.UseCRLF = true

	// s := []string{"hello", "world", "hello", "golang", "hello", "ruby", "php", "java"}
	// urlList := []string{}

	//儲存key
	resultObj := map[string]interface{}{}

	// fmt.Println(removeDuplicateElement(s))
	for {
		record, err := readFile.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Fatalln(err)
		}

		var deviceIdentifiers = record[4]
		var deviceModel = record[5]
		var deviceSubModel = record[6]
		var eventName = record[8]
		var eventParameters = record[10]

		// csvFile.Seek(0, io.SeekEnd)
		// csvFile.WriteString("\xEF\xBB\xBF") // 寫入UTF-8 防止中文亂碼
		// writer := csv.NewWriter(csvFile)
		// writer.Comma = ','
		// writer.UseCRLF = true
		StrContainers := strings.Contains(eventName, "Flurry") //排除系統預設事件,空的 Parameter
		if StrContainers || len(eventParameters) < 5 {
			continue
		}
		if name == "1" && count != 0 {
			name1 := strings.Contains(eventName, "LaunchTime")
			if !name1 {
				continue
			}
		}
		if name == "2" && count != 0 {
			name2 := strings.Contains(eventName, "NetError")
			if !name2 {
				continue
			}
		}
		if name == "3" && count != 0 {
			name3 := strings.Contains(eventName, "SocketError")
			if !name3 {
				continue
			}
		}
		if name == "4" && count != 0 {
			name4 := strings.Contains(eventName, "AndroidSpeed")
			if !name4 {
				continue
			}
		}
		if name == "5" && count != 0 {
			name5 := strings.Contains(eventName, "AppStatus")
			if !name5 {
				continue
			}
		}

		if name == "6" && count != 0 {
			name6 := strings.Contains(eventName, "onClick")
			if !name6 {
				continue
			}
		}

		var responseDatas model.AutoGenerated
		err2 := json.Unmarshal([]byte(eventParameters), &responseDatas)
		if err2 != nil {
			// fmt.Println(err)
		}
		// fmt.Println("Time:", responseDatas.Time)
		if count == 0 {
			VersionInfo = "VersionInfo"
			SocketError = "SocketError"
			Time = "Time"
			UserID = "UserID"
			DeviceID = "DeviceID"
			CurrentLine = "CurrentLine"
			ApiSpeed = "ApiSpeed"
			ContractSpeed = "ContractSpeed"
			LaunchTime = "LaunchTime"
			NetError = "NetError"
			URL = "URL"
			AppStatus = "AppStatus"
			Name = "Name"
			OnClick = "OnClick"
			EventID = "eventID"
			ApiCallTime = "ApiCallTime"
			ApiResponseTime = "ApiResponseTime"
			error300Report = "error300Report"

		} else {
			VersionInfo = responseDatas.VersionInfo
			SocketError = responseDatas.SocketError
			Time = responseDatas.Time
			UserID = responseDatas.UserID
			DeviceID = responseDatas.DeviceID
			CurrentLine = responseDatas.CurrentLine
			ApiSpeed = responseDatas.ApiSpeed
			ContractSpeed = responseDatas.ContractSpeed
			LaunchTime = responseDatas.LaunchTime
			NetError = responseDatas.NetError
			URL = responseDatas.URL
			AppStatus = responseDatas.AppStatus
			Name = responseDatas.Name
			OnClick = responseDatas.OnClick
			EventID = responseDatas.EventID
			ApiCallTime = responseDatas.ApiCallTime
			ApiResponseTime = responseDatas.ResponseTime
			error300Report = responseDatas.Error300Report
		}
		// fmt.Println("deviceIdentifiers :", deviceIdentifiers)
		var responseDatas2 model.DeviceIdentifiers
		err3 := json.Unmarshal([]byte(deviceIdentifiers), &responseDatas2)
		if err3 != nil {
			// fmt.Println(err3)
		}
		//寫入 csv 標頭
		// fmt.Println("count :", count)
		if count == 0 {
			if name == "3" {
				// fmt.Println("count :", count)
				txt := [][]string{{Time, deviceIdentifiers, deviceModel, deviceSubModel, eventName, VersionInfo, SocketError, UserID, DeviceID, URL, Name}}
				writer.WriteAll(txt)

				// writer.Flush()
			} else if name == "1" {
				// fmt.Println("count :", count)
				txt := [][]string{{Time, deviceIdentifiers, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, LaunchTime, URL, Name}}
				writer.WriteAll(txt)

				// writer.Flush()
			} else if name == "2" {
				// fmt.Println("count :", count)
				txt := [][]string{{Time, deviceIdentifiers, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, NetError, URL, Name}}
				writer.WriteAll(txt)

				// writer.Flush()
			} else if name == "7" {
				// fmt.Println("count :", count)
				txt := [][]string{{Time, deviceIdentifiers, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, URL, Name, ApiCallTime}}
				writer.WriteAll(txt)

				// writer.Flush()
			} else if name == "8" {
				// fmt.Println("count :", count)
				txt := [][]string{{Time, deviceIdentifiers, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, URL, Name, ApiResponseTime}}
				writer.WriteAll(txt)

				txt2 := [][]string{{"apiurl", "apiMaxTime", "apiMiniTime", "apiAverageTime", "gwMaxTime", "gwMiniTime", "gwAverageTime", "count"}}
				writer2.WriteAll(txt2)

			} else if name == "9" {
				// fmt.Println("count :", count)
				txt := [][]string{{Time, deviceIdentifiers, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, URL, Name, error300Report}}
				writer.WriteAll(txt)
				// writer.Flush()

			} else {
				// fmt.Println("count :", count)
				txt := [][]string{{Time, deviceIdentifiers, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, CurrentLine, ApiSpeed, ContractSpeed, NetError, URL, Name, EventID, ApiCallTime, ApiResponseTime, error300Report}}
				writer.WriteAll(txt)
				// writer.Flush()

			}
			count = count + 1
		}
		//寫入指定 userid 資料
		if uuid == UserID && len(Time) != 0 {
			Filecount = Filecount + 1
			// fmt.Println("Filecount :", Filecount)
			// fmt.Println("name :", name)
			if name == "3" {
				if eventName == "SocketError" {
					txt := [][]string{{Time, responseDatas2.Idfv, deviceModel, deviceSubModel, eventName, VersionInfo, SocketError, UserID, DeviceID, URL, Name, eventParameters}}
					writer.WriteAll(txt)
				}
			} else if name == "1" {
				if eventName == "LaunchTime" {
					txt := [][]string{{Time, responseDatas2.Idfv, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, LaunchTime, URL, Name, eventParameters}}
					writer.WriteAll(txt)
				}
			} else if name == "2" {
				if eventName == "NetError" {
					txt := [][]string{{Time, deviceIdentifiers, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, NetError, URL, Name, eventParameters}}
					writer.WriteAll(txt)
				}
			} else if name == "7" {
				if eventName == "ApiCallTime" {
					fmt.Println("ApiResponseTime :", ApiCallTime)
					txt := [][]string{{Time, deviceIdentifiers, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, URL, Name, ApiCallTime, eventParameters}}
					writer.WriteAll(txt)
				}
			} else if name == "8" {
				// str1 := strings.Split(VersionInfo, ".")
				// fmt.Println("ver :", str1[len(str1)-1])
				if eventName == "ApiResponseTime" {
					txt := [][]string{{Time, deviceIdentifiers, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, URL, Name, ApiResponseTime, eventParameters}}
					writer.WriteAll(txt)
				}
			} else if name == "9" {
				if eventName == "error300Report" {
					txt := [][]string{{Time, deviceIdentifiers, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, URL, Name, error300Report, eventParameters}}
					writer.WriteAll(txt)
				}
			} else {
				// fmt.Println("Time :", Time)
				txt := [][]string{{Time, responseDatas2.Idfv, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, CurrentLine, ApiSpeed, ContractSpeed, NetError, URL, Name, EventID, ApiCallTime, ApiResponseTime, error300Report, eventParameters}}
				writer.WriteAll(txt)
				// writer.Flush()
			}
		} else if uuid == "root" && len(Time) != 0 {
			// fmt.Println("name :", name)
			Filecount = Filecount + 1
			// txt := [][]string{{Time, responseDatas2.Idfv, deviceModel, deviceSubModel, eventName, VersionInfo, SocketError, UserID, DeviceID, CurrentLine, ApiSpeed, ContractSpeed, LaunchTime, NetError, URL, Name, EventID, eventParameters, ApiCallTime, ApiResponseTime, error300Report}}
			// writer.WriteAll(txt)
			if name == "3" {
				if eventName == "SocketError" {
					txt := [][]string{{Time, responseDatas2.Idfv, deviceModel, deviceSubModel, eventName, VersionInfo, SocketError, UserID, DeviceID, URL, Name, eventParameters}}
					writer.WriteAll(txt)
				}
			} else if name == "1" {
				if eventName == "LaunchTime" {
					txt := [][]string{{Time, responseDatas2.Idfv, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, LaunchTime, URL, Name, eventParameters}}
					writer.WriteAll(txt)
				}
			} else if name == "2" {
				if eventName == "NetError" {
					txt := [][]string{{Time, deviceIdentifiers, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, NetError, URL, Name, eventParameters}}
					writer.WriteAll(txt)
				}
			} else if name == "7" {
				if eventName == "ApiCallTime" {
					txt := [][]string{{Time, deviceIdentifiers, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, URL, Name, ApiCallTime, eventParameters}}
					writer.WriteAll(txt)
				}
				// txt := [][]string{{Time, deviceIdentifiers, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, URL, Name, ApiCallTime, eventParameters}}
				// writer.WriteAll(txt)
			} else if name == "8" {
				str1 := strings.Split(VersionInfo, ".")
				// fmt.Println("ver= ", str1)
				strall := str1[len(str1)-1]
				trimStr := strings.TrimSpace(strall)
				// fmt.Println("trimStr=", trimStr)
				marks2, err := strconv.Atoi(trimStr)
				// fmt.Println("marks2=", marks2)
				if err != nil {
					// fmt.Println("Error during conversion= ", err)
					// return
				}
				// fmt.Println("ver :", str1[len(str1)-1])
				if marks2 >= 28 { //android
					// if marks2 >= 17 { //ios

					if eventName == "ApiResponseTime" || eventName == "ServerResponseTime" {
						txt := [][]string{{Time, deviceIdentifiers, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, URL, Name, ApiResponseTime, eventParameters}}
						writer.WriteAll(txt)

						var responseDatas3 model.ApiCallUrl
						err4 := json.Unmarshal([]byte(eventParameters), &responseDatas3)
						if err4 != nil {
							// fmt.Println(err3)
						}
						// fmt.Println("eventName=", eventName)
						// marksStr := "320"
						marks, err := strconv.Atoi(responseDatas3.SubtractTime) //Android
						// marks, err := strconv.Atoi(responseDatas3.Res_subtract) //iOS

						// fmt.Println("resgw= ", responseDatas3.Res_gw)
						resgw, err9 := strconv.Atoi(responseDatas3.Res_gw) //Android & iOS

						// fmt.Println("responseDatas3.ApiCallUrl= ", responseDatas3.ApiCallUrl)
						// fmt.Println("marks=", marks)
						if err != nil {
							// fmt.Println("Error during conversion")
							// return
						}
						if err9 != nil {
							// fmt.Println("Error during conversion")
							// return
						}

						// fmt.Println(marks)

						var oneObj = map[string]interface{}{
							"ApiCallUrl": responseDatas3.ApiCallUrl,
							"all":        marks,
							"max":        marks,
							"min":        marks,
							"times":      0,
							"count":      1,
							"maxgw":      resgw,
							"mingw":      resgw,
							"allgw":      resgw,
						}

						if resultObj[responseDatas3.ApiCallUrl] == nil {
							resultObj[responseDatas3.ApiCallUrl] = oneObj
						} else {
							tempObj := resultObj[responseDatas3.ApiCallUrl].(map[string]interface{})
							maxcount := tempObj["max"].(int)
							mincount := tempObj["min"].(int)
							maxcountgw := tempObj["maxgw"].(int)
							mincountgw := tempObj["mingw"].(int)
							numcount := tempObj["all"].(int) + marks
							numcountgw := tempObj["allgw"].(int) + resgw
							allcount := tempObj["count"].(int)
							allcount = allcount + 1
							if marks > maxcount {
								maxcount = marks
							}
							if marks < mincount {
								mincount = marks
							}

							if resgw > maxcountgw {
								maxcountgw = resgw
							}
							if resgw < mincountgw {
								mincountgw = resgw
							}

							var oneObj2 = map[string]interface{}{
								"ApiCallUrl": responseDatas3.ApiCallUrl,
								"all":        numcount,
								"max":        maxcount,
								"min":        mincount,
								"times":      0,
								"count":      allcount,
								"maxgw":      maxcountgw,
								"mingw":      mincountgw,
								"allgw":      numcountgw,
							}
							resultObj[responseDatas3.ApiCallUrl] = oneObj2
						}

						// var result map[string]interface{}
						// json_body := []byte(`{"a":92, "b":{"c": "123", "d": 1235}}`)
						// json.Unmarshal(json_body, &result)
						// fmt.Println(result)
						// fmt.Println("============")
						// bResult := result["b"].(map[string]interface{})
						// fmt.Println("c: " + bResult["c"].(string))

						// tempObj := resultObj[responseDatas3.ApiCallUrl]
						// tempObj[max]
						// tempObj["max"].int = tempObj["max"].int + responseDatas3.SubtractTime

						// resultObj[key]["max"] = resultObj[key]["max"] + MAX數字

						// urlList = append(urlList, responseDatas3.ApiCallUrl)
						// num, err := strconv.Atoi(responseDatas3.SubtractTime)
						// if err != nil {
						// 	// fmt.Println(err3)
						// }
						// fmt.Println("count :", count)

						// txt2 := [][]string{{responseDatas3.ApiCallUrl, responseDatas3.SubtractTime, "0", "0"}}
						// writer2.WriteAll(txt2)
					}
				}
				// fmt.Println("count :", str1[str1.l])

				// txt := [][]string{{Time, deviceIdentifiers, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, URL, Name, ApiResponseTime, eventParameters}}
				// writer.WriteAll(txt)
			} else if name == "9" {
				if eventName == "error300Report" {
					txt := [][]string{{Time, deviceIdentifiers, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, URL, Name, error300Report, eventParameters}}
					writer.WriteAll(txt)
				}
				// txt := [][]string{{Time, deviceIdentifiers, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, URL, Name, error300Report, eventParameters}}
				// writer.WriteAll(txt)
			} else {
				txt := [][]string{{Time, responseDatas2.Idfv, deviceModel, deviceSubModel, eventName, VersionInfo, UserID, DeviceID, CurrentLine, ApiSpeed, ContractSpeed, NetError, URL, Name, EventID, ApiCallTime, ApiResponseTime, error300Report, eventParameters}}
				writer.WriteAll(txt)
			}
		}
		count = count + 1
	}
	writer.Flush()
	file.Close()

	if Filecount == 0 {
		fmt.Println("找不到此 Userid :", uuid)
		err := os.Remove(filePaths + fileName) //删除文件
		if err != nil {
			//如果删除失败则输出 file remove Error!
			fmt.Println("File Remove Error!")
			//输出错误详细信息
			fmt.Printf("%s", err)
		} else {
			//如果删除成功则输出 file remove OK!
			fmt.Print("File Remove OK!")

		}
	}

	for k := range resultObj {
		testtxt := resultObj[k].(map[string]interface{})
		maxtxt := strconv.FormatInt(int64(testtxt["max"].(int)), 10)
		mintxt := strconv.FormatInt(int64(testtxt["min"].(int)), 10)
		maxtxtgw := strconv.FormatInt(int64(testtxt["maxgw"].(int)), 10)
		mintxtgw := strconv.FormatInt(int64(testtxt["mingw"].(int)), 10)
		// alltxt := strconv.FormatInt(int64(testtxt["all"].(int)), 10)
		counttxts := strconv.FormatInt(int64(testtxt["count"].(int)), 10)
		// alltxt := strconv.FormatInt(int64(testtxt["allgw"].(int)), 10)

		// var averagetxt2 = "0"
		// if testtxt["count"].(int) != 0 {
		// 	averagetxt := testtxt["all"].(int) / testtxt["count"].(int)
		// 	averagetxt2 = strconv.FormatInt(int64(averagetxt), 10)
		// } else {
		// 	averagetxt2 = alltxt
		// }
		averagetxt := testtxt["all"].(int) / testtxt["count"].(int)
		averagetxt2 := strconv.FormatInt(int64(averagetxt), 10)

		averagetxtgw := testtxt["allgw"].(int) / testtxt["count"].(int)
		averagetxt2gw := strconv.FormatInt(int64(averagetxtgw), 10)
		// txt2 := [][]string{{"apiurl", "apiMaxTime", "apiMiniTime", "apiAverageTime", "gwMaxTime", "gwMiniTime","gwAverageTime"}}

		txt2 := [][]string{{testtxt["ApiCallUrl"].(string), maxtxt, mintxt, averagetxt2, maxtxtgw, mintxtgw, averagetxt2gw, counttxts}}
		// fmt.Println("txt2 :", txt2)
		writer2.WriteAll(txt2)
	}
	writer2.Flush()

}

func getWorkingDirPath() string { //開發模式路徑
	dir, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	// fmt.Println("workingDirPath:", dir)
	return dir
}

func getAbsPath() string {
	dir, err := filepath.Abs(filepath.Dir(os.Args[0]))
	if err != nil {
		panic(err)
	}
	// fmt.Println("absPath:", dir)
	return dir
}

func getExePath() string {
	ex, err := os.Executable()
	if err != nil {
		panic(err)
	}
	exePath := filepath.Dir(ex)
	// fmt.Println("exePath:", exePath)
	return exePath
}

func checkNumber() {
	for {
		fmt.Printf("版本:1.0.7\n")
		fmt.Printf("請輸入要查詢的 UserId: ")
		fmt.Scanln(&uuid)

		if uuid != "" {
			break
		}
	}
	fmt.Println("查詢的 Userid:", uuid)
	for {
		fmt.Printf("1.LaunchTime\n2.NetError\n3.SocketError\n4.AndroidSpeed\n5.AppStatus\n6.onClick\n7.ApiCallTime\n8.ApiResponseTime\n9.error300Report\n")
		fmt.Printf("請輸入要輸出的類型號碼: ")
		fmt.Scanln(&name)

		if name != "" {
			break
		}
	}
	fmt.Println(name)
}

func checkFileName() {
	if name == "1" {
		fileName = "/LaunchTime_" + uuid + ".csv"
	}
	if name == "2" {
		fileName = "/NetError_" + uuid + ".csv"
	}
	if name == "3" {
		fileName = "/SocketError_" + uuid + ".csv"
	}
	if name == "4" {
		fileName = "/AndroidSpeed_" + uuid + ".csv"
	}
	if name == "5" {
		fileName = "/AppStatus_" + uuid + ".csv"
	}
	if name == "6" {
		fileName = "/onClick_" + uuid + ".csv"
	}
	if name == "7" {
		fileName = "/ApiCallTime_" + uuid + ".csv"
	}
	if name == "8" {
		fileName = "/ApiResponseTime_" + uuid + ".csv"
		fileName2 = "/weexrawlist" + ".csv"
	}
	if name == "9" {
		fileName = "/error300Report_" + uuid + ".csv"
	}

	// ApiCallTime = "ApiCallTime"
	// ApiResponseTime = "ApiResponseTime"
	// error300Report = "error300Report"
}

func removeDuplicateElement(addrs []string) []string {
	result := make([]string, 0, len(addrs))
	temp := map[string]struct{}{}
	for _, item := range addrs {
		if _, ok := temp[item]; !ok {
			temp[item] = struct{}{}
			result = append(result, item)
		}
	}
	return result
}
